import { Inter } from "next/font/google";
import "./globals.css";
import { NextThemeProvider } from "@/lib/NextThemeProvider";
import Header from "@/components/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Game Log Truckter",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextThemeProvider> 
          <Header />
        {children}
        </NextThemeProvider>
        </body>
    </html>
  );
}
